gains: [
  "supersoft",
  "soft",
  "tight",
]

gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    ICP: ["supersoft", "soft"]
    VSLAM: ["supersoft", "soft"]
    BRICKFLOW: ["soft"]
    HECTOR: ["soft"]
    ALOAM: ["soft"]
    ALOAMGARM: ["soft"]
    ALOAMREP: ["soft"]
    BRICK: ["supersoft"]
    T265: ["soft"]
    OBJECT: ["supersoft"]
    VIO: ["supersoft"]
    LIDAR: ["supersoft"]
    RTK: ["supersoft", "soft", "tight"]
    OPTFLOWGPS: ["supersoft", "soft", "tight"]
    GPS: ["supersoft", 'soft', 'tight']
    OPTFLOW: ["supersoft", "soft"]
    TOWER: ["supersoft", "soft"]
    OTHER: ["supersoft"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    ICP: "supersoft"
    VSLAM: "supersoft"
    BRICKFLOW: "soft"
    HECTOR: "soft"
    ALOAM: "soft"
    ALOAMGARM: "soft"
    ALOAMREP: "soft"
    BRICK: "supersoft"
    T265: "soft"
    OBJECT: "supersoft"
    VIO: "supersoft"
    LIDAR: "supersoft"
    RTK: "soft"
    OPTFLOWGPS: "soft"
    GPS: "soft"
    OPTFLOW: "supersoft"
    TOWER: "supersoft"
    OTHER: "supersoft"
