So3Controller:
  address: "mrs_uav_controllers/So3Controller"
  namespace: "so3_controller"
  eland_threshold: 2.5 # [m], position error triggering eland
  failsafe_threshold: 5.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 2.0 # [m], position odometry innovation threshold

EmergencyController:
  address: "mrs_uav_controllers/MpcController"
  namespace: "emergency_controller"
  eland_threshold: 5.0 # [m], position error triggering eland
  failsafe_threshold: 10.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 3.0 # [m], position odometry innovation threshold
