darpa:

  horizontal:
    speed: 1.0
    acceleration: 1.0
    jerk: 1.0
    snap: 1.0

  vertical:

    ascending:
      speed: 1.0
      acceleration: 1.0
      jerk: 1.0
      snap: 1.0

    descending:
      speed: 1.0
      acceleration: 1.0
      jerk: 1.0
      snap: 1.0

  yaw:
    speed: 0.5
    acceleration: 0.5
    jerk: 2.0
    snap: 2.0
