rate: 25

estimator_types: [
  "BRICKFLOW",
  "HECTOR",
  "T265",
  "BRICK",
  "VIO",
  "ICP",
  "RTK",
  "OPTFLOWGPS",
  "GPS",
  "OPTFLOW",
  "OTHER",
]

gains: [
  "supersoft",
  "soft",
  "tight",
  "optflow",
  "wall",
]

gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    BRICKFLOW: ["optflow"]
    HECTOR: ["soft", "supersoft", "tight", "optflow"]
    T265: ["soft", "supersoft", "tight"]
    BRICK: ["supersoft"]
    VIO: ["supersoft"]
    ICP: ["supersoft"]
    RTK: ["soft", "supersoft", "tight","wall"]
    OPTFLOWGPS: ["soft", "supersoft"]
    GPS: ["soft", 'supersoft', 'tight','wall']
    OPTFLOW: ["optflow"]
    OTHER: ["supersoft"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    BRICKFLOW: "optflow"
    HECTOR: "optflow"
    T265: "soft"
    BRICK: "supersoft"
    VIO: "supersoft"
    ICP: "supersoft"
    RTK: "soft"
    OPTFLOWGPS: "soft"
    GPS: "soft"
    OPTFLOW: "optflow"
    OTHER: "supersoft"
