# - list of names of dynamically loaded trackers
trackers : [
  "MpcTracker",
  "LineTracker",
  "LandoffTracker",
  "JoyTracker",
  "MatlabTracker",
  "SpeedTracker",
  "FlipTracker",
  "NullTracker",
  "MidairActivationTracker",
]

# - list of names of dynamically loaded controllers
controllers : [
  "Se3Controller",
  "MpcController",
  "FailsafeController",
  "EmergencyController",
  "MidairActivationController",
  "MotorController",
]

safety:

  min_thrust_null_tracker: 0.15 # [] minimum thrust when not flying

  # when the active tracker returns empty command
  tracker_error_action: "ehover" # {eland, ehover}
