supersoft:

  horizontal:
    kp: 2.0
    kv: 1.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 33.3333
    kv: 16.6667
    ka: 1.0

    attitude:
      kq: 20.0
      kw: 5.0

  mass_estimator:
    km: 1.0
    km_lim: 5.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 6.4
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 8.0
      kw: 0.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 50.0
    kv: 30.0
    ka: 1.0

    attitude:
      kq: 1.0
      kw: 0.1

  mass_estimator:
    km: 1.0
    km_lim: 5.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
